#pragma once

// Compile-time ReUWP configuration.
//
// Options default to the production-safe behavior. Define any option from the
// build system to override it for diagnostics or compatibility experiments.

#ifndef REUWP_ENABLE_LOGGING
#define REUWP_ENABLE_LOGGING 1
#endif

#ifndef REUWP_ENABLE_CRASH_REPORTING
#define REUWP_ENABLE_CRASH_REPORTING 1
#endif

#ifndef REUWP_ENABLE_RUNTIME_TRACE
#define REUWP_ENABLE_RUNTIME_TRACE 1
#endif

#ifndef REUWP_ENABLE_WATCHDOG
#define REUWP_ENABLE_WATCHDOG 1
#endif

#ifndef REUWP_ENABLE_COMPAT_DEBUG_ENV
#define REUWP_ENABLE_COMPAT_DEBUG_ENV 1
#endif

#ifndef REUWP_ENABLE_WARP_FALLBACK
#define REUWP_ENABLE_WARP_FALLBACK 0
#endif

#ifndef REUWP_WIN7_FILTER_FEATURE_LEVEL_11_1
#define REUWP_WIN7_FILTER_FEATURE_LEVEL_11_1 1
#endif

#ifndef REUWP_WIN7_DOWNGRADE_D3D_IIDS
#define REUWP_WIN7_DOWNGRADE_D3D_IIDS 1
#endif

#ifndef REUWP_WIN7_RETAIN_BASE_D3D_INTERFACES
#define REUWP_WIN7_RETAIN_BASE_D3D_INTERFACES 1
#endif

#ifndef REUWP_DEFER_INTERACTIVE_RESIZE
#define REUWP_DEFER_INTERACTIVE_RESIZE 1
#endif

#ifndef REUWP_ALT_F4_AS_ESCAPE
#define REUWP_ALT_F4_AS_ESCAPE 1
#endif

#if (REUWP_ENABLE_LOGGING != 0) && (REUWP_ENABLE_LOGGING != 1)
#error REUWP_ENABLE_LOGGING must be 0 or 1
#endif
#if (REUWP_ENABLE_CRASH_REPORTING != 0) && (REUWP_ENABLE_CRASH_REPORTING != 1)
#error REUWP_ENABLE_CRASH_REPORTING must be 0 or 1
#endif
#if (REUWP_ENABLE_RUNTIME_TRACE != 0) && (REUWP_ENABLE_RUNTIME_TRACE != 1)
#error REUWP_ENABLE_RUNTIME_TRACE must be 0 or 1
#endif
#if (REUWP_ENABLE_WATCHDOG != 0) && (REUWP_ENABLE_WATCHDOG != 1)
#error REUWP_ENABLE_WATCHDOG must be 0 or 1
#endif
#if (REUWP_ENABLE_COMPAT_DEBUG_ENV != 0) && (REUWP_ENABLE_COMPAT_DEBUG_ENV != 1)
#error REUWP_ENABLE_COMPAT_DEBUG_ENV must be 0 or 1
#endif

#if (REUWP_ENABLE_WARP_FALLBACK != 0) && (REUWP_ENABLE_WARP_FALLBACK != 1)
#error REUWP_ENABLE_WARP_FALLBACK must be 0 or 1
#endif
#if (REUWP_WIN7_FILTER_FEATURE_LEVEL_11_1 != 0) && (REUWP_WIN7_FILTER_FEATURE_LEVEL_11_1 != 1)
#error REUWP_WIN7_FILTER_FEATURE_LEVEL_11_1 must be 0 or 1
#endif
#if (REUWP_WIN7_DOWNGRADE_D3D_IIDS != 0) && (REUWP_WIN7_DOWNGRADE_D3D_IIDS != 1)
#error REUWP_WIN7_DOWNGRADE_D3D_IIDS must be 0 or 1
#endif
#if (REUWP_WIN7_RETAIN_BASE_D3D_INTERFACES != 0) && (REUWP_WIN7_RETAIN_BASE_D3D_INTERFACES != 1)
#error REUWP_WIN7_RETAIN_BASE_D3D_INTERFACES must be 0 or 1
#endif
#if (REUWP_DEFER_INTERACTIVE_RESIZE != 0) && (REUWP_DEFER_INTERACTIVE_RESIZE != 1)
#error REUWP_DEFER_INTERACTIVE_RESIZE must be 0 or 1
#endif
#if (REUWP_ALT_F4_AS_ESCAPE != 0) && (REUWP_ALT_F4_AS_ESCAPE != 1)
#error REUWP_ALT_F4_AS_ESCAPE must be 0 or 1
#endif
